### ISSUE TITLE
Nginx https error is being produced

### ISSUE THREAD

**Issue by joicemjoseph** [Inbot/bitbucket2gitlab#2]
using this snippet, this is producing an error as follows
`
/usr/lib/ruby/1.9.1/json/common.rb:148:in parse': 746: unexpected token at '<ht (JSON::ParserError) <head><title>400 The plain HTTP request was sent to HTTPS port</title></head> <body bgcolor="white"> <center><h1>400 Bad Request</h1></center> <center>The plain HTTP request was sent to HTTPS port</center> <hr><center>nginx</center> </body> </html> ' from /usr/lib/ruby/1.9.1/json/common.rb:148:inparse'
from ./bitbucket2gitlab.rb:37:in gitlab_key' from ./bitbucket2gitlab.rb:79:in'
`

**Comment by jillesvangurp** [comment]
You may want to turn on/off https depending on your server setup.

But please use the version at https://github.com/gitlabhq/gitlab-recipes.

**Comment by joicemjoseph** [comment]
Actually it is host is gitlab.com and use_ssl flag is true.
